env:
  global:
    secure: zDr/luk9Ps70rkrhp/2iME2dQvabG0/Ny03Qrnt7G5/RS51fR8bWrSfZjvVQsubvOz8MX+JAY0gRpAXMDFm1WJWNpEqsNIj80p4V6YFRU/hKS/00bTE5nTpoqqK5UYXk0Ts1uIK04GmIeuuHaepteY1gvDif42JwuvDpi4gAIADSC0txZdwzus8Hlm1DjZYPbGvB9aKxWB9fklK4EBsBE+brP+jFA88eYWnzGWvTt9X0sKF5KmnkKzoXCJHYzjGsywh5jeKOgtSujWzJSUvhAX6mnUUfN5+44dCLNZYya21zNI4uUyEC8C9BDX32qZ+LCpEO1TF5ddLoCuir4h76D7KNHpq03z09/aiObaey5ofRNbYH7W7Qm0owwwE7dzrBvhpsOTsrc8h4OxZ0XueqtT1JSV4Ma5YP1evqueJOpzL+B5/rgs5Se+eVHIE0oQHUNUN+fC4DxlbsQF7h6Al6MRll/FasTB2MaxVkfeDgSAjJXp8g8n7kLLSKZFH+8+ANnwAQeC3gKxSlGnJ7sSXv3HAfssR6u+DiZwRCOG49QHgbRoJzRJ/rGhZBHlxCIXX/motxjaycAXz5W/dU1J1xTAr5PVjsDdAUN5v1Dt2BPs0A1Mi8kXU+aKf+8NEg1g5GOoTyI6D3hM8+WrGc1WUk05nY0wsm8eEq+Y+5mvAvPWQ=
language: node_js
node_js:
- '5'
install:
- npm i
- npm i -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm registry export github
- jspm i
cache:
  directories:
  - node_modules
  - jspm_packages
after_script:
- gulp karma
- gulp tslint
